version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube"


workflows:
  main:
    jobs:
      - build:
          context: SonarCloud